{"name": "Заказ не принимается, если курьер не найден.", "status": "passed", "description": "Проверяется: тело == \"Курьера с таким id не существует\" и статус код == 404.", "steps": [{"name": "Установка query параметра с идентификатором удаленного курьера", "status": "passed", "start": 1721097503005, "stop": 1721097503005}, {"name": "Получение идентификатора заказа", "status": "passed", "start": 1721097503005, "stop": 1721097505545}, {"name": "Отправка PUT запроса для принятия заказа", "status": "passed", "start": 1721097505545, "stop": 1721097506963}, {"name": "Проверка: ошибка == 'Курьера с таким id не существует'", "status": "passed", "start": 1721097506964, "stop": 1721097506964}, {"name": "Проверка: код ответа == 404", "status": "passed", "start": 1721097506964, "stop": 1721097506964}], "start": 1721097503005, "stop": 1721097506964, "uuid": "6d23cbe0-1bd8-4fc0-bab0-3fd5e33a95fb", "historyId": "cac6689a9ed342d2c9201c93b794b599", "testCaseId": "cac6689a9ed342d2c9201c93b794b599", "fullName": "tests.test_order_accept.TestOrderAccept#test_order_accept_courier_not_found_order_not_accepted", "labels": [{"name": "suite", "value": "PUT /api/v1/orders/accept/:id"}, {"name": "tag", "value": "@pytest.mark.usefixtures('cleanup_users', 'setup_deleted_order_and_courier')"}, {"name": "parentSuite", "value": "tests"}, {"name": "subSuite", "value": "TestOrderAccept"}, {"name": "host", "value": "C02DQ0GHMD6R"}, {"name": "thread", "value": "78646-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_order_accept"}]}