{"name": "Заказ не принимается, если заказ не найден.", "status": "passed", "description": "Проверяется: тело == \"Этот заказ уже в работе\" и статус код == 409.", "steps": [{"name": "Получение идентификатора курьера", "status": "passed", "start": 1721097506966, "stop": 1721097509404}, {"name": "Отправка PUT запроса для принятия заказа", "status": "passed", "start": 1721097509404, "stop": 1721097510680}, {"name": "Проверка: ошибка == 'Этот заказ уже в работе'", "status": "passed", "start": 1721097510680, "stop": 1721097510680}, {"name": "Проверка: код ответа == 409", "status": "passed", "start": 1721097510680, "stop": 1721097510680}], "start": 1721097506966, "stop": 1721097510681, "uuid": "616856ea-2680-4ddd-bc25-0292f2fc2f25", "historyId": "1d3d08855bf4a3b0e1727ea5fc8b2812", "testCaseId": "1d3d08855bf4a3b0e1727ea5fc8b2812", "fullName": "tests.test_order_accept.TestOrderAccept#test_order_accept_order_not_found_order_not_accepted", "labels": [{"name": "suite", "value": "PUT /api/v1/orders/accept/:id"}, {"name": "tag", "value": "@pytest.mark.usefixtures('cleanup_users', 'setup_deleted_order_and_courier')"}, {"name": "parentSuite", "value": "tests"}, {"name": "subSuite", "value": "TestOrderAccept"}, {"name": "host", "value": "C02DQ0GHMD6R"}, {"name": "thread", "value": "78646-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_order_accept"}]}